package com.ai_dlc.workshop.ai;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.transformer.splitter.TokenTextSplitter;
import org.springframework.ai.vectorstore.SimpleVectorStore;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring AI configuration for ingestion pipeline components.
 *
 * <p>Token cost note: {@link TokenTextSplitter} does not call any remote model;
 * it counts tokens locally. Embeddings are generated by {@link VectorStore#add} —
 * each chunk triggers one embedding call. With chunk-size=800 and a typical
 * 2 MB document (~600 k characters / ~150 k tokens), expect ~190 chunks → ~190
 * embedding calls per document upload. At text-embedding-3-small pricing
 * (~$0.02 / 1 M tokens) that is roughly $0.003 per document.
 */
@Configuration
public class AiConfig {

    @Value("${app.ai.rag.chunk-size:800}")
    private int chunkSize;

    // Minimum character length a chunk must have to be sent to the embedding model.
    // Short trailing chunks below this threshold are discarded rather than embedded.
    // Note: TokenTextSplitter does not implement sliding-window overlap in M5.
    @Value("${app.ai.rag.min-chunk-size-chars:200}")
    private int minChunkSizeChars;

    /**
     * Shared text splitter used by {@link IngestionService}.
     * Parameters are tunable via {@code app.ai.rag.chunk-size} and
     * {@code app.ai.rag.min-chunk-size-chars} in application configuration.
     *
     * <p>Uses the builder API to preserve the library's default punctuation marks
     * (required by Spring AI 2.0.0-M5 which asserts the list is non-empty).
     */
    @Bean
    public TokenTextSplitter tokenTextSplitter() {
        return TokenTextSplitter.builder()
                .withChunkSize(chunkSize)
                .withMinChunkSizeChars(minChunkSizeChars)
                .withMinChunkLengthToEmbed(5)
                .withMaxNumChunks(10000)
                .withKeepSeparator(true)
                .build();
    }

    /**
     * Stateless {@link ChatClient} used by {@link com.ai_dlc.workshop.chat.ChatService}.
     * Built from the auto-configured {@link ChatModel} provided by the OpenAI starter.
     */
    @Bean
    public ChatClient chatClient(ChatModel chatModel) {
        return ChatClient.builder(chatModel).build();
    }

    /**
     * Fallback in-memory vector store active when the Azure auto-configuration
     * is excluded (dev profile with no Azure credentials, or test profile).
     *
     * <p>In production the {@code spring-ai-starter-vector-store-azure} starter
     * creates an {@code AzureVectorStore} bean, so this method is skipped via
     * {@link ConditionalOnMissingBean}.
     *
     * <p>Required application.properties keys (Azure / prod):
     * <pre>
     * spring.ai.vectorstore.azure.url=https://&lt;search-name&gt;.search.windows.net
     * spring.ai.vectorstore.azure.api-key=&lt;admin-key&gt;
     * spring.ai.vectorstore.azure.index-name=&lt;index-name&gt;
     * </pre>
     */
    @Bean
    @ConditionalOnMissingBean(VectorStore.class)
    public VectorStore simpleVectorStore(EmbeddingModel embeddingModel) {
        return SimpleVectorStore.builder(embeddingModel).build();
    }
}
