package com.ai_dlc.workshop.ai;

import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.transformer.splitter.TokenTextSplitter;
import org.springframework.ai.vectorstore.SimpleVectorStore;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring AI configuration for ingestion pipeline components.
 *
 * <p>Token cost note: {@link TokenTextSplitter} does not call any remote model;
 * it counts tokens locally. Embeddings are generated by {@link VectorStore#add} —
 * each chunk triggers one embedding call. With chunk-size=800 and a typical
 * 2 MB document (~600 k characters / ~150 k tokens), expect ~190 chunks → ~190
 * embedding calls per document upload. At text-embedding-3-small pricing
 * (~$0.02 / 1 M tokens) that is roughly $0.003 per document.
 */
@Configuration
public class AiConfig {

    @Value("${app.ai.rag.chunk-size:800}")
    private int chunkSize;

    @Value("${app.ai.rag.chunk-overlap:200}")
    private int chunkOverlap;

    /**
     * Shared text splitter used by {@link IngestionService}.
     * Parameters are tunable via {@code app.ai.rag.chunk-size} and
     * {@code app.ai.rag.chunk-overlap} in application configuration.
     */
    @Bean
    public TokenTextSplitter tokenTextSplitter() {
        return new TokenTextSplitter(chunkSize, chunkOverlap, 5, 10000, true);
    }

    /**
     * Fallback in-memory vector store active when the Azure auto-configuration
     * is excluded (dev profile with no Azure credentials, or test profile).
     *
     * <p>In production the {@code spring-ai-starter-vector-store-azure} starter
     * creates an {@code AzureVectorStore} bean, so this method is skipped via
     * {@link ConditionalOnMissingBean}.
     *
     * <p>Required application.properties keys (Azure / prod):
     * <pre>
     * spring.ai.vectorstore.azure.url=https://&lt;search-name&gt;.search.windows.net
     * spring.ai.vectorstore.azure.api-key=&lt;admin-key&gt;
     * spring.ai.vectorstore.azure.index-name=&lt;index-name&gt;
     * </pre>
     */
    @Bean
    @ConditionalOnMissingBean(VectorStore.class)
    public VectorStore simpleVectorStore(EmbeddingModel embeddingModel) {
        return SimpleVectorStore.builder(embeddingModel).build();
    }
}
